FROM python:3.12.2-slim

RUN apt update && \
 apt-get install -y build-essential python3-dev libpcre3 libpcre3-dev

RUN pip install uwsgi

WORKDIR /app
ADD apps/adb-api .
RUN pip3 install -r requirements.txt


CMD ["uwsgi","uwsgi.ini"]